version: '3.7'

services:
  harriet-vision-nursery:
    container_name: harriet-vision-nursery
    build: .
    ports:
      - "8000:8000"
    environment:
      - OUTPUT=/etc/harriet/output
      - INPUT=/etc/harriet/input
    volumes:
      - ${HIGHLIGHTS_OUTPUT}:/etc/harriet/output
      - ${IMAGES_INPUT}:/etc/harriet/input
